### ISSUE TITLE
For Node issues

### ISSUE THREAD

**Issue by Speedevs** [open-ibc/ibc-app-solidity-template#36]
For node Js issues

First use

sudo apt-get update

sudo apt-get install build-essential checkinstall libssl-dev

curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash

sudo npm cache clean -f
sudo npm install -g n
sudo n stable

Use this command for Ubuntu 

This need to be added for node js

**Comment by tmsdkeys** [comment]
Hey @Speedevs thanks for your contribution! Although important, we do consider setup of node and other prerequisites out of scope for this repo. 

But please share your comment in the [Developer Forum: Technical Questions](https://forum.polymerlabs.org/c/technical-questions/19) 🙏
