### ISSUE TITLE
How to fix cannot find module

### ISSUE THREAD

**Issue by Speedevs** [open-ibc/ibc-app-solidity-template#38]
https://discord.com/channels/839903468750635039/1213267408370794506/1215270257405468692

Hello, edit:

scripts/create-channel-config.js

Change:
```
const { getDispatcher } = require('./_get-vibc-sc.js');
```
to
```
const { getDispatcher } = require('./_vibc-helpers.js');
```

**Comment by tmsdkeys** [comment]
THanks for reporting, was fixed in #37
