### ISSUE TITLE
Step bt Step Install Just Dependencies

### ISSUE THREAD

**Issue by jipan76** [open-ibc/ibc-app-solidity-template#43]
First you need to instal Snap
sudo apt install snapd

And then instal Just by rum this command
sudo snap install --edge just --classic

**Comment by tmsdkeys** [comment]
Hey @jipan76  thanks for your contribution! Although important, we do consider setup of just and other prerequisites out of scope for this repo. 

But please share your comment in the [Developer Forum: Technical Questions](https://forum.polymerlabs.org/c/technical-questions/19) 🙏
