### ISSUE TITLE
To Instal Node Js 20_x Version

### ISSUE THREAD

**Issue by akunpromoteid** [open-ibc/ibc-app-solidity-template#44]
First update:
sudo apt update

Install nodejs 20_x with this command:
curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash - &&\
sudo apt-get install -y nodejs

ceck node version:
node -v

**Comment by tmsdkeys** [comment]
Hey @akunpromoteid thanks for your contribution! Although important, we do consider setup of node and other prerequisites out of scope for this repo. 

But please share your comment in the [Developer Forum: Technical Questions](https://forum.polymerlabs.org/c/technical-questions/19) 🙏
