### ISSUE TITLE
 Official document copywriting error

### ISSUE THREAD

**Issue by snakeeeeeeeee** [open-ibc/ibc-app-solidity-template#49]
url：https://docs.polymerlabs.org/docs/quickstart/start/#-install-dependencies

![image](https://github.com/open-ibc/ibc-app-solidity-template/assets/26361007/cfe9c315-f095-45f5-83f8-e0e3d67eecd2)

This should be just do-it.

**Comment by kenobijon** [comment]
This issue has now been fixed
